# Generated by Django 5.2.8 on 2025-11-25 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва страви')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes_photos/', verbose_name='Фото')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_available', models.BooleanField(default=True, verbose_name='Наявність')),
                ('tags', models.CharField(blank=True, choices=[('SPICY', 'Гостре'), ('SWEET', 'Солодке'), ('VEGAN', 'Вегетаріанське'), ('MEAT', 'Мясне')], max_length=20, null=True, verbose_name='Теги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu_api.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('sums', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Загальна сума')),
                ('status', models.CharField(choices=[('NEW', 'Новий'), ('IN_PROGRESS', 'В роботі'), ('COMPLETED', 'Готово')], default='NEW', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна на момент замовлення')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_api.dish', verbose_name='Страва')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_api.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Деталь замовлення',
                'verbose_name_plural': 'Деталі замовлень',
                'unique_together': {('order', 'dish')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата відгуку')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu_api.dish', verbose_name='Страва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'unique_together': {('dish', 'user')},
            },
        ),
    ]
